version: '3.1'
services:
  calories-calculator-mongodb:
    image: mongo:latest
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/data/db
    ports:
        - 27017:27017
    command: mongod --smallfiles --logpath=/dev/null # --quiet

  calories-calculator:
    image: viartemev/calories-calculator:latest
    restart: always
    ports:
      - 8080:8080
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - SPRING_DATA_MONGODB_URI=mongodb://calories-calculator-mongodb:27017/calories-calculator
    depends_on:
      - calories-calculator-mongodb
