spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: calories-calculator

logging:
  level:
    root: INFO
    com.viartemev.calories: INFO

bot:
  token:
  log-level: BASIC